nombre = input("ingrese su nombre ")
comision = input("ingrese su comision ")
asignatura = (input ("ingrese su asignatura "))
docente = input("nombre del docente ")
asistencia = input("asistencia ")
print ("nombre:", nombre)
print ("comision:", comision)
print ("asignatura:", asignatura)
print ("docente:", docente)
print ("asistencia:", asistencia)